### ISSUE TITLE
How to know what I selected in dropdown box.

### ISSUE THREAD

**Issue by stories2** [hitron-cctv/cms#18]
## Problem File Name
_Components.html
## Expected behavior
When I select one item in dropdown box, then get that item text and show selected item.
## Actual behavior
Just showing dropdown box.
## Steps to reproduce the behavior
- Open _Components.html
- Select random item in dropdown box component.

**Comment by rebel1324** [comment]
###Getting Clicked Dropdown Menu Button 
JSFiddle Example: http://jsfiddle.net/cmcculloh/xnpf1rr9/

with combination of custom class, We can get which one is active or not.
`htmlObject.getClass('active')`
